### ISSUE TITLE
Problem beim Erkennen des Reisezeitraums

### ISSUE THREAD

**Issue by diddyhsv** [traveldealz/farerules-explainer#13]
Link zur Fare-Rule: https://trello-attachments.s3.amazonaws.com/5935a8b7d437df7b3e4cd4b1/60e60fe0eaac8b6c78560eab/0904fa37f2001941cb70c7c98a4f1747/LH__LLPT8LGT_FRA-NYC.txt

Explain gibt folgenden Text aus:
Buchbar ist der Tarif für Abflüge zwischen dem . Der Tarif hat kein Ablaufdatum, kann aber trotzdem jederzeit zurückgezogen werden. Der Mindestaufenthalt beträgt 6 Tage. Der maximale Aufenthalt beträgt 12 Monate. Die Tickets werden in Buchungsklasse L ausgestellt und müssen mindestens 14 Tage vor Abflug gebucht werden. Stopover sind nicht erlaubt.

Dabei steht in den Fare Rules folgendes:
Category 3: Seasonal restrictions
  FROM GERMANY -
    PERMITTED 18OCT 20 THROUGH 22DEC 21 OR 28DEC 21 THROUGH
    08APR 22 OR 17APR 22 THROUGH 30JUN 22 OR 16AUG 22
    THROUGH 21DEC 22 OR 28DEC 22 THROUGH 31DEC 22 FOR EACH
    TRANSATLANTIC SECTOR.
  TO GERMANY -
    PERMITTED 18OCT 20 THROUGH 25DEC 21 OR 10JAN 22 THROUGH
    15APR 22 OR 24APR 22 THROUGH 14JUL 22 OR 30AUG 22
    THROUGH 25DEC 22 FOR EACH TRANSATLANTIC SECTOR.

**Comment by goaround** [comment]
Fixed https://github.com/traveldealz/farerules-explainer/pull/14
